apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: noteopx-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - api.dev.noteopx.com
      secretName: tls-secret
  rules:
    - host: api.dev.noteopx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway-svc
                port:
                  number: 30000
