apiVersion: apps/v1
kind: Deployment
metadata:
  name: notication-deploy
  labels:
    app: notification-deploy
    tier: backend
spec:
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      name: notification-pod
      labels:
        app: notification
        tier: backend
    spec:
      containers:
        - name: notification-container
          image: noteopx/notification:14
          imagePullPolicy: Always
          ports:
            - containerPort: 30002
          volumeMounts:
            - name: protos
              mountPath: /notes-protos-nodejs
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: notification_node_env
            - name: PROD_HOST
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: notification_database_host
            - name: PROD_DB
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: notification_database_name
            - name: PROD_USER
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: notification_database_username
            - name: PROD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: notification_database_password
            - name: PROD_PORT
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: notification_database_port
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: notification_service_port
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: encryption_key
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: jwt_token
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: sendgrid_api_key
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: firebase_api_key
            - name: rabbitmqurl
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: rabbitmq_service_url
            - name: MESSAGE_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: message_sender_id
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: app_id
            - name: MEASUREMENT_ID
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: measurement_id
        - name: init-sync-ctr
          image: k8s.gcr.io/git-sync/git-sync:v3.5.0
          volumeMounts:
            - name: protos
              mountPath: /notes-protos-nodejs
          resources: {}
          env:
            - name: GIT_SYNC_SUBMODULES
              value: "recursive"
            - name: GIT_SYNC_REPO
              value: "https://github.com/cocoon-letters-limited/notes-protos-nodejs.git"
            - name: GIT_SYNC_USERNAME
              value: "cocoon-engineering"
            - name: GIT_SYNC_PASSWORD
              value: "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"
            - name: GIT_SYNC_BRANCH
              value: master
            - name: GIT_SYNC_ROOT
              value: /notes-protos-nodejs
            - name: GIT_SYNC_DEST
              value: "data"
      volumes:
        - name: protos
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  labels:
    app: notification-svc
spec:
  # type: LoadBalancer
  selector:
    app: notification
  ports:
    - name: http
      port: 30002
      targetPort: 30002
