apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-deploy
  labels:
    app: subscription-deploy
    tier: backend
spec:
  selector:
    matchLabels:
      app: subscription-management
  template:
    metadata:
      name: subscription-management-pod
      labels:
        app: subscription-management
        tier: backend
    spec:
      containers:
        - name: subscription-management-container
          image: noteopx/subscription-magt:2
          imagePullPolicy: Always
          ports:
            - containerPort: 30004
          volumeMounts:
            - name: protos
              mountPath: /notes-protos-nodejs
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: mongo_url
            - name: PROTO_PATH
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: proto_path
            - name: PAYSTACK_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: paystack_base_url
            - name: PAYSTACK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: paystack_secret_key
            - name: CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: callback_url
            - name: LICENCE_KEY_LEN
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: licence_key_len
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: user-management-secret
                  key: subscription_service_port
        - name: init-sync-ctr
          image: k8s.gcr.io/git-sync/git-sync:v3.5.0
          volumeMounts:
            - name: protos
              mountPath: /notes-protos-nodejs
          resources: {}
          env:
            - name: GIT_SYNC_SUBMODULES
              value: "recursive"
            - name: GIT_SYNC_REPO
              value: "https://github.com/cocoon-letters-limited/notes-protos-nodejs.git"
            - name: GIT_SYNC_USERNAME
              value: "cocoon-engineering"
            - name: GIT_SYNC_PASSWORD
              value: "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"
            - name: GIT_SYNC_BRANCH
              value: master
            - name: GIT_SYNC_ROOT
              value: /notes-protos-nodejs
            - name: GIT_SYNC_DEST
              value: "data"
      volumes:
        - name: protos
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-svc
  labels:
    app: subscription-svc
spec:
  # type: LoadBalancer
  selector:
    app: subscription-management
  ports:
    - name: http
      port: 30004
      targetPort: 30004
