apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
    tier: backend
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: test-pod
      labels:
        app: test
        tier: backend
    spec:
      containers:
        - name: test-container
          image: noteopx/test:30
          imagePullPolicy: Always
          ports:
            - containerPort: 30004
          # volumeMounts:
          #   - name: protos
          #     mountPath: /notes-protos-nodejs
        # - name: init-sync-ctr
        #   image: k8s.gcr.io/git-sync/git-sync:v3.5.0
        #   volumeMounts:
        #     - name: protos
        #       mountPath: /notes-protos-nodejs
        #   resources: {}
        #   env:
        #     - name: GIT_SYNC_SUBMODULES
        #       value: "recursive"
        #     - name: GIT_SYNC_REPO
        #       value: "https://github.com/cocoon-letters-limited/notes-protos-nodejs.git"
        #     - name: GIT_SYNC_USERNAME
        #       value: "cocoon-engineering"
        #     - name: GIT_SYNC_PASSWORD
        #       value: "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"
        #     - name: GIT_SYNC_BRANCH
        #       value: master
        #     - name: GIT_SYNC_ROOT
        #       value: /notes-protos-nodejs
        #     - name: GIT_SYNC_DEST
        #       value: "data"

      volumes:
        - name: protos
          emptyDir: {}
