apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
    tier: backend
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: test-pod
      labels:
        app: test
        tier: backend
    spec:
      initContainers:
        - name: clone-repo
          image: alpine/git
          env:
            - name: GIT_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: token
          command: ["/bin/sh", "-c"]
          args:
            - |
              clone
              https://github.com/my-org/my-repo.git
              /app
      containers:
        - name: test-container
          image: noteopx/test:15
          imagePullPolicy: Always
          ports:
            - containerPort: 30004
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          emptyDir: {}
